
all: tictactoe tic_test comptBanc

tictactoe: 
	g++ ticTacToe_main.cpp ticTacToe.cpp ticTacToe.h -o tictactoe.out -Wall -std=c++11
	
tic_test: 
	g++ ticTacToe_test.cpp ticTacToe.cpp ticTacToe.h -o tic_test.out -Wall -std=c++11
	
comptBanc: 
	g++ comptBanc.cpp comptBanc_test.cpp comptBanc.h -o comptBanc.out -Wall -std=c++11
	
.PHONY: tictactoe
.PHONY: tic_test
.PHONY: comptBanc
